### ISSUE TITLE
Looking for a way to handshake with two smarthphones in order to link two users as friends

### ISSUE THREAD

**Issue by tercierp** [SwEnt-Group8/Street-work-app#16]
- [x] Design the MVVM
- [x] Search and list all the technologies for the handshake process
- [x] Evaluate the list of technologies for our implementation

**Comment by tercierp** [comment]
I completed an initial implementation diagram and evaluated various solutions on the [Technical Design Document
](https://app.eraser.io/workspace/9S7VAxhkJNyRGixYJ55v?origin=share)

Don't hesitate to suggest improvements or other implementation ideas before the next sprint !

**Comment by alvaro1080** [comment]
Thank you for your Technical Design Document; it is particularly well-written.

I would like to add a few comments about the pros and cons:

I think that the high range of Bluetooth is, for our specific situation, a disadvantage. In the context of an app that aims to make people see each other, the distance is definitely not coherent with our goal. On the other hand, the low range of NFC is definitely a plus for our app.

I would also think that the QR code system has the advantage of being well-known and perhaps already used by our potential users, or at least more than the NFC technology. This might have a small impact on the user experience.

Even with those few comments, I have the same conclusion as you: I think that NFC is the best solution for our app.
