### ISSUE TITLE
Fix the current park implementation in Park MVVM

### ISSUE THREAD

**Issue by SaturneV** [SwEnt-Group8/Street-work-app#75]
### Description

Changes the data type of the current park stored in the Park MVVM

### Tasks

- Change current park data type to StateFlow in MVVM park files
- Modifying Park MVVM tests

**Comment by tercierp** [comment]
Originally this issue was resolved in Arthur's PR but he had personal problems so i took over his task. In order to make rapid progress on the M2 project
